database:
  host: localhost
  port: 5432
  username: fileaccount
  password: 1234
  dbname: file_service
  sslmode: disable

server:
  port: 8090
  host: localhost

policy:
  users:
    bootstrapServers: localhost:9092
    topic: users
    groupID: file_service
    timeout: 1
