// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package dto

type File struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	FolderID  string  `json:"folderId"`
	Type      *string `json:"type"`
	Extension *string `json:"extension"`
	Size      *int    `json:"size"`
	Modified  *string `json:"modified"`
	Path      *string `json:"path"`
	UserID    string  `json:"userId"`
}

type Folder struct {
	ID       string  `json:"id"`
	Name     string  `json:"name"`
	ParentID *string `json:"parentId"`
	Path     *string `json:"path"`
	UserID   string  `json:"userId"`
}
